### ISSUE TITLE
SurvivalFly problem

### ISSUE THREAD

**Issue by phonyfakeorreal** [NoCheatPlus/Docs#1]
When a player that is flying legitimately falls while fly sprinting (by double tapping space) they fail SurvivalFly with a VL of around 100 - 120. This applies to both players in creative and survival mode that have getAllowFlight() set to true. I should also note that SurvivalFly is failed when the player is flying without sprinting and falling too, but it's not as easy to trigger.

Steps to reproduce:
Allow flight (via gamemode 1 or /fly)
Sprint fly (Pressing Ctrl while flying)
Double tap space to disable flight while still sprining
Should fail SurvivalFly

Sorry if this isn't the correct place to place issues, the NoCheatPlus repo did not have a /issues page.

**Comment by asofold** [comment]
Sorry for the late reply, we are not on top of our own docs yet.

This is indeed the wrong place for tickets concerning issues with using the plugin/code, this is just for issues with the documentation itself.

Concerning the issue - i think there exists tickets on BukkitDev (see README.md of the NoCheatPlus project) already and we are aware of mode-transitions being problematic.
