### ISSUE TITLE
Typo in "[Moving] Passable"

### ISSUE THREAD

**Issue by HunterGPlays** [NoCheatPlus/Docs#2]
https://github.com/NoCheatPlus/Docs/wiki/%5BMoving%5D-Passable

"raytracing active" is spelled as "raytracing acrive".

**Comment by MyPictures** [comment]
Ops. Thanks! Fixed now and will be merged on the next update: https://github.com/NoCheatPlus/Docs/commit/7d93b99ad18ff3bf25673013b7797f028b0fa9a2
